### ISSUE TITLE
Un-responsive

### ISSUE THREAD

**Issue by rwishavg** [rwishavg/Forward#19]
The index and login page are not yet responsive for mobile devices.

**Comment by Nirodha-Github** [comment]
I would like to modify index and login pages to responsive pages using bootstrap.

**Comment by rwishavg** [comment]
> I would like to modify index and login pages to responsive pages using bootstrap.

Please go ahead. What i would reccomend is that you try to avoid using bootstap unless absolutely necessary. Also create a new branch under your name.

**Comment by Nirodha-Github** [comment]
Ok.I will try to do without using bootstrap

**Comment by rwishavg** [comment]
I had asked you to create your own branch and not push into main branch. The pages have not been designed properly yet. I reccomend you try and minimise white spaces and spread elements out evenly.
